#!/bin/sh

##############################################################################
#  Gradle start up script for POSIX generated by Gradle.
##############################################################################

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")
DEFAULT_JVM_OPTS="-Xmx4096m -Xms512m"

PRG="$0"
while [ -h "$PRG" ]; do
    ls=$(ls -ld "$PRG")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then PRG="$link"; else PRG=$(dirname "$PRG")"/$link"; fi
done
SAVED="$(pwd)"
cd "$(dirname "$PRG")/" >/dev/null
APP_HOME="$(pwd -P)"
cd "$SAVED" >/dev/null

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use
if [ -n "$JAVA_HOME" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi

# Download gradle wrapper jar if missing
WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
if [ ! -e "$WRAPPER_JAR" ]; then
    echo "ERROR: gradle-wrapper.jar not found at $WRAPPER_JAR"
    exit 1
fi

# Determine the wrapper properties
WRAPPER_PROPERTIES="$APP_HOME/gradle/wrapper/gradle-wrapper.properties"
if [ ! -e "$WRAPPER_PROPERTIES" ]; then
    echo "ERROR: gradle-wrapper.properties not found"
    exit 1
fi

# Extract distribution URL from properties
DIST_URL=$(grep 'distributionUrl' "$WRAPPER_PROPERTIES" | sed 's/.*distributionUrl=//' | sed 's/\\:/:/g')

# Check if gradle distribution is already cached
GRADLE_USER_HOME="${GRADLE_USER_HOME:-${HOME}/.gradle}"
DIST_PATH=$(echo "$DIST_URL" | sed 's/.*\///' | sed 's/\.zip$//')
CACHED_DIST="$GRADLE_USER_HOME/wrapper/dists/$DIST_PATH"

exec "$JAVACMD" \
    $DEFAULT_JVM_OPTS $JAVA_OPTS \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"